#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-rentrez
Version  : 1.2.4
Release  : 45
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/rentrez_1.2.4.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/rentrez_1.2.4.tar.gz
Summary  : 'Entrez' in R
Group    : Development/Tools
License  : MIT
Requires: R-XML
Requires: R-httr
Requires: R-jsonlite
BuildRequires : R-XML
BuildRequires : R-httr
BuildRequires : R-jsonlite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
allowing users to search databases like 'GenBank'

%prep
%setup -q -n rentrez
pushd ..
cp -a rentrez buildavx2
popd
pushd ..
cp -a rentrez buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749680393

%install
export SOURCE_DATE_EPOCH=1749680393
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rentrez/CITATION
/usr/lib64/R/library/rentrez/DESCRIPTION
/usr/lib64/R/library/rentrez/INDEX
/usr/lib64/R/library/rentrez/LICENSE
/usr/lib64/R/library/rentrez/Meta/Rd.rds
/usr/lib64/R/library/rentrez/Meta/features.rds
/usr/lib64/R/library/rentrez/Meta/hsearch.rds
/usr/lib64/R/library/rentrez/Meta/links.rds
/usr/lib64/R/library/rentrez/Meta/nsInfo.rds
/usr/lib64/R/library/rentrez/Meta/package.rds
/usr/lib64/R/library/rentrez/Meta/vignette.rds
/usr/lib64/R/library/rentrez/NAMESPACE
/usr/lib64/R/library/rentrez/NEWS.md
/usr/lib64/R/library/rentrez/R/rentrez
/usr/lib64/R/library/rentrez/R/rentrez.rdb
/usr/lib64/R/library/rentrez/R/rentrez.rdx
/usr/lib64/R/library/rentrez/doc/index.html
/usr/lib64/R/library/rentrez/doc/rentrez_tutorial.R
/usr/lib64/R/library/rentrez/doc/rentrez_tutorial.Rmd
/usr/lib64/R/library/rentrez/doc/rentrez_tutorial.html
/usr/lib64/R/library/rentrez/help/AnIndex
/usr/lib64/R/library/rentrez/help/aliases.rds
/usr/lib64/R/library/rentrez/help/paths.rds
/usr/lib64/R/library/rentrez/help/rentrez.rdb
/usr/lib64/R/library/rentrez/help/rentrez.rdx
/usr/lib64/R/library/rentrez/html/00Index.html
/usr/lib64/R/library/rentrez/html/R.css
/usr/lib64/R/library/rentrez/tests/test-all.R
/usr/lib64/R/library/rentrez/tests/testthat/test_api_key.r
/usr/lib64/R/library/rentrez/tests/testthat/test_citmatch.r
/usr/lib64/R/library/rentrez/tests/testthat/test_docs.r
/usr/lib64/R/library/rentrez/tests/testthat/test_fetch.r
/usr/lib64/R/library/rentrez/tests/testthat/test_httr.r
/usr/lib64/R/library/rentrez/tests/testthat/test_httr_post.r
/usr/lib64/R/library/rentrez/tests/testthat/test_info.r
/usr/lib64/R/library/rentrez/tests/testthat/test_link.r
/usr/lib64/R/library/rentrez/tests/testthat/test_net.r
/usr/lib64/R/library/rentrez/tests/testthat/test_parse.r
/usr/lib64/R/library/rentrez/tests/testthat/test_post.r
/usr/lib64/R/library/rentrez/tests/testthat/test_query.r
/usr/lib64/R/library/rentrez/tests/testthat/test_search.r
/usr/lib64/R/library/rentrez/tests/testthat/test_summary.r
/usr/lib64/R/library/rentrez/tests/testthat/test_webenv.r
